<div id="sidebar" class="column-left">
<ul>
<li><a href="/obscamp/1999KW4/index.shtml" title="Top Level Home Page for the 1999 KW4 Observing Campaign"><strong>Campaign Home page</strong></a></li>
<li><a href="/obscamp/1999KW4/1999KW4_status.shtml" title="Current status of NEA 1999 KW4">Current Status</a></li>
<!-- <li><a href="/obscamp/1999KW4/1999KW4_2019.shtml" title="Details about the 2019 close approach of NEA 1999 KW4">2019 Apparition</a></li> -->
<li><a href="/obscamp/1999KW4/1999KW4_properties.shtml" title="Physical and chemical properties that are known about NEA 1999 KW4.">Physical Properties</a></li>

<li><a href="/obscamp/1999KW4/1999KW4_obs.shtml" title="Information about planned, scheduled and in-hand observations of NEA 1999 KW4">Observations</a></li>
<li><a href="/obscamp/1999KW4/1999KW4_orbit.shtml" title="Information about the current orbit of NEA 1999 KW4">Orbit</a></li>
<li><a href="/obscamp/1999KW4/1999KW4_geometry.shtml" title="Geometry and other information about observing conditions for NEA 1999 KW4">Observing Geometry</a></li>
<!-- <li><a href="/obscamp/1999KW4/1999KW4_history.shtml" title="History and interesting facts about NEA 1999 KW4">History</a></li> -->
<!-- <li><a href="/obscamp/1999KW4/1999KW4_media.shtml" title="Press releases and news related to NEA 1999 KW4">Media</a></li> -->
<li><a href="/obscamp/1999KW4/1999KW4_gallery.shtml" title="NEA 1999 KW4 gallery">Gallery</a></li>
<!-- <li><a href="/obscamp/1999KW4/project/" title="NEA 1999 KW4 project">Project</a></li> -->
</ul>

<hr />
<h4>Related Links</h4>
<ul>
<li><a href="https://www.nasa.gov/planetarydefense" title="">Planetary Defense Coordination Office</a></li>
<li><a href="https://pdssbn.astro.umd.edu/" title="">NASA PDS: Small Bodies Node</a></li>
<li><a href="http://www.minorplanetcenter.net/" title="">Minor Planet Center (MPC)</a></li>
<li><a href="http://iawn.net//" title="">International Asteroid Warning Network</a></li>
<li><a href="https://cneos.jpl.nasa.gov/" title="">Center for Near Earth Object Studies</a></li>
</ul>

<hr />
<h4>Observing Campaigns</h4>
<ul>
<li><a href="http://wirtanen.astro.umd.edu/" title="UMD site that serves as a central clearinghouse for basic information regarding comet 46P/Wirtanen (WERE-tuh-nun) to encourage and facilitate the acquisition, analysis and interpretation of observations, and to promote collaborations between researchers.">The Comet Wirtanen Campaign</a></li>
<li><a href="http://www.psi.edu/41P45P46P" title="Continuation of a campaign begun during ISON and is aimed at achieving science objectives facilitated by multi-longitudinal observations during the close approaches of comets 41P/Tuttle-Giacobini-Kresak (hereafter 41P/TGK) and 45P/Honda-Mrkos-Pajdusakova (hereafter 45P/HMP) in 2017 and comet 46P/Wirtanen in 2018.">4*P Coma Morphology Campaign</a></li>
<li><a href="http://aop.astro.umd.edu" title="UMD Program designed to inspire and educate amateur astronomers at all levels in observing celestial objects. Originally set up to encourage and collect amateur observations of NEA 9P/Tempel 1 in support of the Deep Impact mission, the AOP has since been used to support observations of a number of other high profile comets and asteroids. It is also a great site for beginners to learn about astrophotography, and more experienced observers to learn how to improve their skills.">Comets &amp; Asteroids Collaborative Astronomy Observers</a></li>
</ul>

<!-- <hr/>
<ul style="margin:-1px 0 -3px 0; background-color:#1BDAEB">
<li><a href="/obscamp/1999KW4/contact.shtml"title="Contact Us web form"><strong>Contact Us</strong></a></li>
</ul> -->

</div>