<div id="sidebar" class="column-left">
<ul>
<li><a href="/obscamp/3I_ATLAS/index.shtml" title="Top Level Home Page for the 3I/ATLAS Astrometry Campaign"><strong>Campaign Home page</strong></a></li>
<li><a href="/obscamp/3I_ATLAS/3I_geometry.shtml" title="Geometry and other information about observing conditions for 3I/ATLAS">Observing Geometry</a></li>
<li><a href="/obscamp/3I_ATLAS/3I_orbit.shtml" title="Information about the current orbit of 3I/ATLAS">Orbit</a></li>
<!-- <li><a href="/obscamp/3I_ATLAS/3I_summary.shtml" title="Timing Summary of 3I/ATLAS">Astrometry Summary</a></li> -->


</ul>

<hr />
<h4>Related Links</h4>
<ul>
<li><a href="http://iawn.net//" title="">International Asteroid Warning Network</a></li>
<li><a href="https://www.nasa.gov/planetarydefense" title="">Planetary Defense Coordination Office</a></li>
<li><a href="https://pdssbn.astro.umd.edu/" title="">NASA PDS: Small Bodies Node</a></li>
<li><a href="http://www.minorplanetcenter.net/" title="">Minor Planet Center (MPC)</a></li>
<li><a href="https://cneos.jpl.nasa.gov/" title="">Center for Near Earth Object Studies</a></li>
</ul>

<!-- <hr />
<h4>Observing Campaigns</h4>
<ul>
<li><a href="http://wirtanen.astro.umd.edu/" title="UMD site that serves as a central clearinghouse for basic information regarding comet 46P/Wirtanen (WERE-tuh-nun) to encourage and facilitate the acquisition, analysis and interpretation of observations, and to promote collaborations between researchers.">The Comet Wirtanen Campaign</a></li>
<li><a href="http://www.psi.edu/41P45P46P" title="Continuation of a campaign begun during ISON and is aimed at achieving science objectives facilitated by multi-longitudinal observations during the close approaches of comets 41P/Tuttle-Giacobini-Kresak (hereafter 41P/TGK) and 45P/Honda-Mrkos-Pajdusakova (hereafter 45P/HMP) in 2017 and comet 46P/Wirtanen in 2018.">4*P Coma Morphology Campaign</a></li>
<li><a href="http://aop.astro.umd.edu" title="UMD Program designed to inspire and educate amateur astronomers at all levels in observing celestial objects. Originally set up to encourage and collect amateur observations of NEA 9P/Tempel 1 in support of the Deep Impact mission, the AOP has since been used to support observations of a number of other high profile comets and asteroids. It is also a great site for beginners to learn about astrophotography, and more experienced observers to learn how to improve their skills.">Comets &amp; Asteroids Collaborative Astronomy Observers</a></li>
</ul> -->

<!-- <hr/>
<ul style="margin:-1px 0 -3px 0; background-color:#1BDAEB">
<li><a href="/obscamp/3I_ATLAS/contact.shtml"title="Contact Us web form"><strong>Contact Us</strong></a></li>
</ul> -->

</div>