<h2>Observing Geometry for the 2029 Apparition</h2>

<p>The plots presented here are for general planning purposes. If you need more detailed values for the different geometric conditions, use the JPL Horizons routines to compute the values for your specific situation.</p>

<p>Geometry was computed using the orbital solution JPL#199.</p>

<hr /><br />
<h3>Geometry Data File</h3>
<p></p>
<p>The geometric data plotted below is included in ASCII format in this <a href="Geometry/2029/Apophis_geometry.dat">Data File</a>.</p>


<h3>Right Ascension and Declination</h3>
<p>Note that the width of the line reflects the objects estimated brightness, which is plotted below.</p>
<p><a href="Geometry/2029/Apophis_RA_Dec.png" title="2029 RA and Dec positions"><img src="Geometry/2029/Apophis_RA_Dec.png" width="100%" alt="2029 Plot of the object's RA And Dec positions" /></a>
<br /><a href="Geometry/2029/Apophis_RA_Dec.pdf">PDF Version</a></p>

<hr /><br />
<h3>Heliocentric and Geocentric Distances</h3>
<p><a href="Geometry/2029/Apophis_dist.png" title="2029 Heliocentric and geocentric distances"><img src="Geometry/2029/Apophis_dist.png" width="100%" alt="2029 Plot of Heliocentric and Geocentric Distances" /></a>
<br /><a href="Geometry/2029/Apophis_dist.pdf">PDF Version</a></p>

<hr /><br />
<h3>Solar Elongation and Solar Phase Angle</h3>
<p><a href="Geometry/2029/Apophis_ang.png" title="2029 Solar Elongation and Phase Angle"><img src="Geometry/2029/Apophis_ang.png" width="100%" alt="2029 Solar Elongation and Phase Angle" /></a>
<br /><a href="Geometry/2029/Apophis_ang.pdf">PDF Version</a></p>
Expanded view of the angles around close approach:
<p><a href="Geometry/2029/Apophis_ang2.png" title="2029 Solar Elongation and Phase Angle - Expanded view"><img src="Geometry/2029/Apophis_ang2.png" width="100%" alt="2029 Solar Elongation and Phase Angle - Expanded view" /></a>
<br /><a href="Geometry/2029/Apophis_ang2.pdf">PDF Version</a></p>

<hr /><br />
<h3>Rate of Motion</h3>
<p>
<a href="Geometry/2029/Apophis_rates.png" title="2029 Rate"><img src="Geometry/2029/Apophis_rates.png" width="48%" alt="2029 Rate" /></a>
<a href="Geometry/2029/Apophis_rates2.png" title="2029 Rate"><img src="Geometry/2029/Apophis_rates2.png" width="48%" alt="2029 Rate" /></a>
<br /><a href="Geometry/2029/Apophis_rates.pdf">Apophis_rates.pdf</a>
<br /><a href="Geometry/2029/Apophis_rates2.pdf">Apophis_rates2.pdf</a>
</p>

<hr /><br />
<h3>Predicted Brightness</h3>
<p><a href="Geometry/2029/Apophis_bright.png" title="2029 Predicted Brightness"><img src="Geometry/2029/Apophis_bright.png" width="100%" alt="2029 Predicted Brightness" /></a>
<br /><a href="Geometry/2029/Apophis_bright.pdf">PDF Version</a></p>

<hr /><br />
<h3>True Anomaly</h3>
<p>Notice that the true anomaly may have a discontinuity at close approach, which is caused by the changes in the asteroid's orbit from the gravitational effects of the Earth.</p>
<p><a href="Geometry/2029/Apophis_trueanom.png" title="2029 True Anomaly"><img src="Geometry/2029/Apophis_trueanom.png" width="100%" alt="2029 True Anomaly" /></a>
<br /><a href="Geometry/2029/Apophis_trueanom.pdf">PDF Version</a></p>

<br />
<hr />
<br />

<h2>Rise, set and visibility from different latitudes</h2>
<p> The asteroid rises and sets at different times depending on the observer's latitude and longitude. The plots below provide information for approximating when the asteroid will be visible, and how long it will be observable from a given location on a given date.</p>
<p>Plots are given for latitude intervals of 5&deg;, which is usually close enough for general planning purposes. Rise and set times are given in UTC for 0&deg; longitude. For other latitudes, these times will be approximate to the local time, which should again be sufficient for basic planning purposes. Note, however, that there will be an offset (typically &lt; 1/2 hr) for different longitudes, so if more accuracy is needed, then you should obtain a more detailed ephemeris.</p>

<h3>How to read these plots</h3>
<p>We provide a more detailed description of the Rise/Set and visibility plots, and an example of how to read the information <a href="Rise_Set/Rise_set_description.pdf" title="Explanation of how to read the	 Rise/Set and visibility (TimeUp) plots">here (PDF).</a></p>

<br />

<h3>Asteroid visibility (TimeUp) and Rise/Set plots</h3>
<p>If there is another major observatory for which you'd like to see details, please let <script type="text/javascript" language="JavaScript">
document.write('<a h'+'ref="m'+'ailt'+'o:'+'%77%61%72%6e%65%72%65%6d%40%61%73%74%72%6f%2e%75%6d%64%2e%65%64%75">&#69;&#108;&#105;&#122;&#97;&#98;&#101;&#116;&#104;&#32;&#87;&#97;&#114;&#110;&#101;&#114;<\/a>');
</script> know.</p>
<table style="width:85%; border-spacing:0px;">

<colgroup>
<col width="35%" />
<col width="25%" />
<col width="25%" />
</colgroup>

<tr>
<th></th>
<th colspan="2">2029 Encounter</th>
</tr>

<tr>
<td align="right">Goldstone (+35.4)</td>
<td><a href="Timeup/2029/Apophis_timeup_2029_CA_Goldstone.pdf" title="Goldstone, Timeup">Timeup</a></td>
<td><a href="Rise_Set/2029/Apophis_riseset_2029_CA_Goldstone.pdf" title="Goldstone, Rise/Set">Rise/Set</a></td>
</tr>

<tr>
<td align="right">DCT (+34.7)</td>
<td><a href="Timeup/2029/Apophis_timeup_2029_CA_DCT.pdf" title="DCT, Timeup">Timeup</a></td>
<td><a href="Rise_Set/2029/Apophis_riseset_2029_CA_DCT.pdf" title="DCT, Rise/Set">Rise/Set</a></td>
</tr>

<tr>
<td align="right">Spacewatch (+32)</td>
<td><a href="Timeup/2029/Apophis_timeup_2029_CA_Spacewatch.pdf" title="Spacewatch, Timeup">Timeup</a></td>
<td><a href="Rise_Set/2029/Apophis_riseset_2029_CA_Spacewatch.pdf" title="Spacewatch, Rise/Set">Rise/Set</a></td>
</tr>

<tr>
<td align="right">La Palma (+28.8)</td>
<td><a href="Timeup/2029/Apophis_timeup_2029_CA_LaPalma.pdf" title="La Palma, Timeup">Timeup</a></td>
<td><a href="Rise_Set/2029/Apophis_riseset_2029_CA_LaPalma.pdf" title="La Palma, Rise/Set">Rise/Set</a></td>
</tr>

<tr>
<td align="right">IRTF (+19.8)</td>
<td><a href="Timeup/2029/Apophis_timeup_2029_CA_IRTF.pdf" title="IRTF, Timeup">Timeup</a></td>
<td><a href="Rise_Set/2029/Apophis_riseset_2029_CA_IRTF.pdf" title="IRTF, Rise/Set">Rise/Set</a></td>
</tr>

<tr>
<td align="right">Arecibo (+18.4)</td>
<td><a href="Timeup/2029/Apophis_timeup_2029_CA_Arecibo.pdf" title="Arecibo, Timeup">Timeup</a></td>
<td><a href="Rise_Set/2029/Apophis_riseset_2029_CA_Arecibo.pdf" title="Arecibo, Rise/Set">Rise/Set</a></td>
</tr>

<tr>
<td align="right">La Silla (-29)</td>
<td><a href="Timeup/2029/Apophis_timeup_2029_CA_LaSilla.pdf" title="La Silla, Timeup">Timeup</a></td>
<td><a href="Rise_Set/2029/Apophis_riseset_2029_CA_LaSilla.pdf" title="La Silla, Rise/Set">Rise/Set</a></td>
</tr>

<tr>
<td align="right">CTIO (-30.2)</td>
<td><a href="Timeup/2029/Apophis_timeup_2029_CA_CTIO.pdf" title="CTIO, Timeup">Timeup</a></td>
<td><a href="Rise_Set/2029/Apophis_riseset_2029_CA_CTIO.pdf" title="CTIO, Rise/Set">Rise/Set</a></td>
</tr>

<tr>
<td align="right">Sutherland (-32.4)</td>
<td><a href="Timeup/2029/Apophis_timeup_2029_CA_Sutherland.pdf" title="CTIO, Timeup">Timeup</a></td>
<td><a href="Rise_Set/2029/Apophis_riseset_2029_CA_Sutherland.pdf" title="CTIO, Rise/Set">Rise/Set</a></td>
</tr>

</table>
