<h2>Orbit of Asteroid 99942 Apophis 2021</h2>

<p><img src="/obscamp/Apophis/gallery/apophis-orbital-parameters.png" width="300" class="left" alt="" />Orbital elements listed here are taken from the <a href="https://ssd.jpl.nasa.gov/horizons.cgi#top">JPL Horizons website</a>, and represent the current best solution. The orbit will only be perturbed slightly during the close approach to the Earth, but we still provide the Keplerian elements for both the pre- and post-Earth encounter. </p>

<h3>Orbital Elements (Solution JPL#199)</h3>
<table style="width:100%; border-spacing:0px;">


<tr>
<td>Epoch</td>
<td>2459279.54166  2021-Mar-06.0</td>
</tr>

<tr>
<td>Perihelion Time</td>
<td>T = 2021-Jul-29 02:26:34 UT</td>
</tr>

<tr>
<td>Perihelion Time (JD)</td>
<td>T = 2459424.601782 </td>
</tr>

<tr>
<td>Orbital Period</td>
<td>P = 0.8859 yr</td>
</tr>

<tr>
<td>Semi-major Axis</td>
<td>a = 0.9224 au</td>
</tr>

<tr>
<td>Perihelion Distance</td>
<td>q = 0.7457 AU</td>
</tr>

<tr>
<td>Eccentricity</td>
<td>e = 0.1916</td>
</tr>

<tr>
<td>Inclination (J2000)</td>
<td>i = 3.34&deg;</td>
</tr>

<tr>
<td>Ascending Node (J2000)</td>
<td>&Omega; = 203.99&deg;</td>
</tr>

<tr>
<td>Argument of Perihelion (J2000)</td>
<td>&omega; = 126.66&deg;</td>
</tr>

<tr>
<td></td>
<td></td>
<td></td>
</tr>

<tr>
<td><strong>Perigee Time</strong></td>
<td>t = 2021-Mar-06 01:06 UT</td>
<td></td>
</tr>

<tr>
<td><strong>Perigee Distance</strong></td>
<td>&Delta; = 0.1126 AU
<br/>&Delta; = 1.685&times;10<sup>7</sup> km</td>
</tr>

<tr>
<td><strong>Velocity with respect to Earth <br /> at closest approach</strong></td>
<td>4.658 km/s</td>
<td></td>
</tr>

<tr>
<td><strong>Min. Orbital Intersection Dist. </strong></td>
<td>MOID = 0.0003156 AU</td>
</tr>

<tr>
<td></td>
<td></td>
</tr>

</table>


<h3>Full Orbit From Above</h3>
<p>View of Asteroid 99942 Apophis 2021's pre-encounter orbit as seen from the North ecliptic pole with the asteroid and planets shown at the time of the asteroid's closest approach to Earth. <i>From the JPL Small-Body Database Browser.</i></p>
<p><a href="Orbits/2021/Apophis_orbit_full.png" title="View of Apophis' full orbit"><img src="Orbits/2021/Apophis_orbit_full.png" width="80%" alt="View of Apophis' entire orbit." /></a></p>
<br/>

<h3>Orbit in Oblique View</h3>
<p>Oblique view of the portion of Asteroid 99942 Apophis 2021's orbit around perigee, viewed from 30&deg; above the ecliptic plane. The black dot denotes the asteroid's and Earth's positions at perigee (2019-May-25). 
<br /><a href="Orbits/2021/Apophis_orbit_plot.png" title="Oblique view of Apophis' orbit"> <img src="Orbits/2021/Apophis_orbit_plot.png" width="80%" alt="Oblique view of Apophis' orbit." /></a> 
<br /><a href="Orbits/2021/Apophis_orbit_plot.pdf">PDF Version</a></p>


<h3>Orbit in Earth Co-Orbital View</h3>
<p>The orbit of Asteroid 99942 Apophis 2021 around perihelion, in the Earth's co-orbital reference frame, as seen from above (top panel) and in the ecliptic plane (bottom panel). The black circle denotes the asteroid's position at perihelion (2019-Mar-22) and the open circles show positions at 30-day intervals.
<br /><a href="Orbits/2021/Apophis_orbit_plot_corot.png" title="Orbit of Apophis in the Earth co-orbital reference frame"> <img src="Orbits/2021/Apophis_orbit_plot_corot.png" width="80%" alt="Plot of Apophis' orbit in Earth-co-orbital frame."/></a>
<br /><a href="Orbits/2021/Apophis_orbit_plot_corot.pdf">PDF Version</a></p>