<h2>Orbit of Asteroid 99942 Apophis 2029</h2>

<p><img src="/obscamp/Apophis/gallery/apophis-orbital-parameters.png" width="300" class="left" alt="example parameters" />Orbital elements listed below are taken from the <a href="https://ssd.jpl.nasa.gov/horizons.cgi#top">JPL Horizons website</a>, and represent the current best solution. The orbit will only be perturbed slightly during the close approach to the Earth, but we still provide the Keplerian elements for both the pre- and post-Earth encounter. </p>

<h3>Orbital Elements (Solution JPL#218)</h3>
<table style="width:100%; border-spacing:0px;">


<tr>
<td>Epoch</td>
<td>2460600.5 2024-Oct-17.0</td>
</tr>

<tr>
<td>Perihelion Time</td>
<td>T = 2025-Feb-12.85355952 TDB</td>
</tr>

<tr>
<td>Perihelion Time (JD)</td>
<td>T = 2460719.353559523448</td>
</tr>

<tr>
<td>Orbital Period</td>
<td>P = 0.88588 yr</td>
</tr>

<tr>
<td>Semi-major Axis</td>
<td>a = 0.92238 au</td>
</tr>

<tr>
<td>Perihelion Distance</td>
<td>q = 0.74607 AU</td>
</tr>

<tr>
<td>Eccentricity</td>
<td>e = 0.19115</td>
</tr>

<tr>
<td>Inclination (J2000)</td>
<td>i = 3.34&deg;</td>
</tr>

<tr>
<td>Ascending Node (J2000)</td>
<td>&Omega; = 203.904&deg;</td>
</tr>

<tr>
<td>Argument of Perihelion (J2000)</td>
<td>&omega; = 126.672&deg;</td>
</tr>

<tr>
<td></td>
<td></td>
<td></td>
</tr>

<tr>
<td><strong>Perigee Time</strong></td>
<td>t = ??</td>
<td></td>
</tr>

<tr>
<td><strong>Perigee Distance</strong></td>
<td>&Delta; = ?? AU
<br/>&Delta; = ??&times;10<sup>7</sup> km</td>
</tr>

<tr>
<td><strong>Velocity with respect to Earth <br /> at closest approach</strong></td>
<td>?? km/s</td>
<td></td>
</tr>

<tr>
<td><strong>Min. Orbital Intersection Dist. </strong></td>
<td>MOID = 0.?? AU</td>
</tr>

</table>


<h3>Full Orbit From Above</h3>
<p>View of Asteroid 99942 Apophis 2029's orbit as seen from the North ecliptic pole with the asteroid and planets shown at the time of the asteroid's closest approach to Earth. <i>From the JPL Small-Body Database Browser.</i></p>
<p><a href="Orbits/2029/Apophis_orbit_2029.png" title="View of Apophis' full orbit"><img src="Orbits/2029/Apophis_orbit_2029.png" width="80%" alt="View of Apophis' entire orbit." /></a></p>
<br/>

<h3>Orbit in Oblique View</h3>
<p>Oblique view of the portion of Asteroid 99942 Apophis 2029's orbit around perigee, viewed from 30&deg; above the ecliptic plane. The black dot denotes the asteroid's and Earth's positions at perigee (YYYY-Mon-DD). 
<br /><a href="Orbits/2029/Apophis_orbit_plot.png" title="Oblique view of Apophis' orbit"> <img src="Orbits/2029/Apophis_orbit_plot.png" width="80%" alt="Oblique view of Apophis' orbit." /></a> 
<br /><a href="Orbits/2029/Apophis_orbit_plot.pdf">PDF Version</a></p>


<h3>Orbit in Earth Co-Orbital View</h3>
<p>The orbit of Asteroid 99942 Apophis 2029 around perihelion, in the Earth's co-orbital reference frame, as seen from above (top panel) and in the ecliptic plane (bottom panel). The black circle denotes the asteroid's position at perihelion (YYYY-Mon-DD) and the open circles show positions at 30-day intervals.
<br /><a href="Orbits/2029/Apophis_orbit_plot_corot.png" title="Orbit of Apophis in the Earth co-orbital reference frame"> <img src="Orbits/2029/Apophis_orbit_plot_corot.png" width="80%" alt="Plot of Apophis' orbit in Earth-co-orbital frame."/></a>
<br /><a href="Orbits/2029/Apophis_orbit_plot_corot.pdf">PDF Version</a></p>