<!-- footer row content -->

<div class="art-content-layout">
<div class="art-content-layout-row">

<div class="art-layout-cell layout-item-0" style="width: 33%">
<p class="art-page-footer">Copyright &copy; 2025. All Rights Reserved.
<br /><a href="https://umd.edu/web-accessibility" onclick="this.target='_blank'">Web Accessibility</a>
<br /><a href="http://www.artisteer.com/" onclick="this.target='_blank'">Web Template</a> created with Artisteer.</p>
</div>

<div class="art-layout-cell layout-item-0" style="width: 34%">
<a href="/misc/contacts.shtml">Contact</a> | <a href="/misc/links.shtml">Links</a> | <a href="/misc/credits.shtml">Credits</a>
<br /><a href="https://pdssbn.astro.umd.edu/" title="Small Bodies Node">PDS-SBN</a> | <a href="https://www.minorplanetcenter.net/" title="Minor Planet Center">MPC</a> | <a href="https://www.nasa.gov/planetarydefense" title="Planetary Defense Coordination Office">PDCO</a> | <a href="https://www.cosmos.esa.int/web/smpag" title="Space Mission Planning Advisory Group">SMPAG</a>
</div>

<div class="art-layout-cell layout-item-0" style="width: 33%">
<p class="art-page-footer">IAWN Mgr: <a href='ma&#105;&#108;to&#58;%6D&#37;6F%6Fnyguy&#64;&#103;ma%&#54;&#57;l&#46;c&#111;m'>&#x44;&#x72;&#x2e;&#x20;&#x56;&#x69;&#x73;&#x68;&#x6e;&#x75;&#x20;&#x52;&#x65;&#x64;&#x64;&#x79;</a>
<br />SBN PI: <a href='mailto&#58;&#103;erb&#115;&#98;&#64;as&#116;r%6F&#46;umd&#46;&#37;&#54;5d&#37;7&#53;'>&#x44;&#x72;&#x2E;&#x20;&#x47;&#x65;&#x72;&#x62;&#x73;&#x20;&#x42;&#x61;&#x75;&#x65;&#x72;</a>
<br />Web: <a href='m&#97;ilt&#111;&#58;&#119;ar&#110;ere&#109;&#64;&#37;61s&#37;7&#52;ro&#37;2&#69;u&#109;d&#46;&#101;d&#37;7&#53;'>&#x45;&#x6C;&#x69;&#x7A;&#x61;&#x62;&#x65;&#x74;&#x68;&#x20;&#x57;&#x61;&#x72;&#x6E;&#x65;&#x72;</a></p>
</div>

</div>
</div>

<!-- end footer row content -->