
<p>Asteriod designation: 2024 YR4
<br />Discovery station: ATLAS Chile
<br />Close approach date (UTC): 2032 12 22.59
<br />Close approach distance (&times; lunar distance): 0.02
<br /><a href="https://minorplanetcenter.net/mpec/K24/K24YE0.html^M" onclick="this.target='_blank'">Discovery announcement</a>
<br /><a href="https://minorplanetcenter.net/db_search/show_object?object_id=2024+YR4^M" onclick="this.target='_blank'">Latest orbit &amp; observations</a>
</p>
