<!-- ############################## Start menu_geometry.inc ############################## -->

<div class="art-layout-cell art-sidebar1">
<div class="art-vmenublock clearfix">
<div class="art-vmenublockcontent">

<ul class="art-vmenu">
<li><a href="/index.shtml">Home</a></li>
<li><a href="/about.shtml">About IAWN</a>
	<ul>
	<li><a href="/about/members.shtml">Members</a></li>
	<li><a href="/about/members.shtml#join_IAWN">How to Join IAWN</a></li>
	</ul></li>
<li><a href="/meetings.shtml">Meetings and Notes</a></li>
<li><a href="/close-approaches.shtml">CLOSE APPROACHES</a></li>
<li><a href="/campaigns.shtml">Observing</a></li>
<li><a href="/misc/links.shtml">Links</a></li>
<li><a href="/misc/contacts.shtml">Contacts</a></li>
</ul>

</div><!-- close class=art-vmenublockcontent -->
</div><!-- close class=art-vmenublock clearfix -->
</div><!-- close class=art-layout-cell art-sidebar1 -->

<!-- ############################## Start menu_geometry.inc ############################## -->
