
<!-- Google Analytics -->
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-DQPHPE6HZ3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-DQPHPE6HZ3');
</script>



<!-- Created by Artisteer v4.3.0.60745 -->
<meta charset="UTF-8">
<meta name="viewport" content="initial-scale = 1.0, maximum-scale = 1.0, user-scalable = no, width = device-width" />

<!--[if lt IE 9]>
<script src="https://html5shiv.googlecode.com/svn/trunk/html5.js">
</script>
<![endif]-->
<link rel="stylesheet" href="/css-n-inc/style.css" media="screen" />
<!--[if lte IE 7]>
<link rel="stylesheet" href="/css-n-inc/style.ie7.css" media="screen" />
<![endif]-->
<link rel="stylesheet" href="/css-n-inc/style.responsive.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Merriweather&amp;subset=latin" />

<script src="/css-n-inc/jquery.js">
</script>
<script src="/css-n-inc/script.js">
</script>
<script src="/css-n-inc/script.responsive.js">
</script>
<script src="/css-n-inc/sorttable.js">
</script>

</head>
<body>
<div id="art-main">
<div class="art-sheet clearfix">
<header class="art-header">

<div class="art-shapes">
<div class="art-object1140172892"></div>
</div><!-- close class=art-shapes -->

</header>

<!-- BEGIN Maintenance banner -->
<!-- 
<table class="important">
<tr>
<td><h1>DOWNTIME ANNOUNCEMENT</h1>
<h3>Intermittent network outages due to network upgrades by the university and department:</h3>
<ul>
<li>EST 10pm Thu 8 Jan thru 7pm Fri 9 Jan</li>
</ul>
<p>Thank you for your patience.</p>
</td>
</tr>
</table>
 -->
<!-- END Maintenance banner -->

<div class="art-layout-wrapper">
<div class="art-content-layout">
<div class="art-content-layout-row">

