<div id="sidebar" class="column-left">
	<ul>
	<li><a href="/obscamp/2024YR4/index.shtml" title="Top Level Home Page for the 2024&nbsp;YR4"><strong>2024&nbsp;YR4 Home</strong></a></li>
	<li><a href="/obscamp/2024YR4/2024YR4_obs.shtml" title="Information about planned, scheduled and in-hand observations of 2024&nbsp;YR4">Observations</a></li>
	<li><a href="http://iawn.net//" title="">International Asteroid Warning Network</a></li>
	</ul>
</div>