<div id="sidebar" class="column-left">
<ul>
<li><a href="/obscamp/2025FA22/index.shtml" title="Top Level Home Page for the 2025&nbsp;FA22 Characterization Campaign"><strong>Campaign Home page</strong></a></li>
<li><a href="/obscamp/2025FA22/2025FA22_obs.shtml" title="Information about planned, scheduled and in-hand observations of 2025&nbsp;FA22">Obs. Planning Tables</a></li>
<li><a href="/obscamp/2025FA22/2025FA22_orbit.shtml" title="Information about the current orbit of 2025&nbsp;FA22">Orbit</a></li>
<li><a href="/obscamp/2025FA22/2025FA22_geometry.shtml" title="Geometry and other information about observing conditions for 2025&nbsp;FA22">Observing Geometry</a></li>
<li><a href="/obscamp/2025FA22/2025FA22_gallery.shtml" title="images, animations, lightcurves, spectrometry... 2025&nbsp;FA22">Gallery</a></li>
<li><a href="/obscamp/2025FA22/2025FA22_summary.shtml" title="Campaign Summary of 2025&nbsp;FA22">Campaign Summary</a></li>
</ul>


<hr />
<h4>Related Links</h4>
<ul>
<li><a href="http://iawn.net//" title="">International Asteroid Warning Network</a></li>
<li><a href="https://www.nasa.gov/planetarydefense" title="">Planetary Defense Coordination Office</a></li>
<li><a href="https://pdssbn.astro.umd.edu/" title="">NASA PDS: Small Bodies Node</a></li>
<li><a href="http://www.minorplanetcenter.net/" title="">Minor Planet Center (MPC)</a></li>
<li><a href="https://cneos.jpl.nasa.gov/" title="">Center for Near Earth Object Studies</a></li>
</ul>



<!-- <hr/>
<ul style="margin:-1px 0 -3px 0; background-color:#1BDAEB">
<li><a href="/obscamp/2025FA22/contact.shtml"title="Contact Us web form"><strong>Contact Us</strong></a></li>
</ul> -->

</div>